/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VintedResult } from './VintedResult';
import {
    VintedResultFromJSON,
    VintedResultFromJSONTyped,
    VintedResultToJSON,
} from './VintedResult';

/**
 * 
 * @export
 * @interface ItemsResult
 */
export interface ItemsResult {
    /**
     * 
     * @type {boolean}
     * @memberof ItemsResult
     */
    done: boolean;
    /**
     * 
     * @type {Array<VintedResult>}
     * @memberof ItemsResult
     */
    results: Array<VintedResult>;
}

/**
 * Check if a given object implements the ItemsResult interface.
 */
export function instanceOfItemsResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "done" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function ItemsResultFromJSON(json: any): ItemsResult {
    return ItemsResultFromJSONTyped(json, false);
}

export function ItemsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemsResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'done': json['done'],
        'results': ((json['results'] as Array<any>).map(VintedResultFromJSON)),
    };
}

export function ItemsResultToJSON(value?: ItemsResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'done': value.done,
        'results': ((value.results as Array<any>).map(VintedResultToJSON)),
    };
}

