/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestIdResult
 */
export interface RequestIdResult {
    /**
     * 
     * @type {string}
     * @memberof RequestIdResult
     */
    requestId: string;
}

/**
 * Check if a given object implements the RequestIdResult interface.
 */
export function instanceOfRequestIdResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "requestId" in value;

    return isInstance;
}

export function RequestIdResultFromJSON(json: any): RequestIdResult {
    return RequestIdResultFromJSONTyped(json, false);
}

export function RequestIdResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestIdResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestId': json['request_id'],
    };
}

export function RequestIdResultToJSON(value?: RequestIdResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'request_id': value.requestId,
    };
}

