/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VintedResult
 */
export interface VintedResult {
    /**
     * 
     * @type {string}
     * @memberof VintedResult
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof VintedResult
     */
    thumbnailUrl: string;
    /**
     * 
     * @type {string}
     * @memberof VintedResult
     */
    dominantColor: string;
    /**
     * 
     * @type {string}
     * @memberof VintedResult
     */
    dominantColorOpaque: string;
}

/**
 * Check if a given object implements the VintedResult interface.
 */
export function instanceOfVintedResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "thumbnailUrl" in value;
    isInstance = isInstance && "dominantColor" in value;
    isInstance = isInstance && "dominantColorOpaque" in value;

    return isInstance;
}

export function VintedResultFromJSON(json: any): VintedResult {
    return VintedResultFromJSONTyped(json, false);
}

export function VintedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): VintedResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'thumbnailUrl': json['thumbnail_url'],
        'dominantColor': json['dominant_color'],
        'dominantColorOpaque': json['dominant_color_opaque'],
    };
}

export function VintedResultToJSON(value?: VintedResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'thumbnail_url': value.thumbnailUrl,
        'dominant_color': value.dominantColor,
        'dominant_color_opaque': value.dominantColorOpaque,
    };
}

